### ISSUE TITLE
access Tencent API failed

### ISSUE THREAD

**Issue by aojiaodemeng** [serverless/serverless-tencent#15]
### BUG 描述:
云函数终端部署过程中出现“access Tencent API failed, get empty response”

### 复现步骤:
1.终端执行部署命令：sls deploy
2.点击终端界面出现的登录链接进行登录
3.终端出现如下错误提示：
![image](https://user-images.githubusercontent.com/35892254/120884695-2e674780-c617-11eb-9c1c-d56ab3fb531b.png)

![image](https://user-images.githubusercontent.com/35892254/120884962-daf5f900-c618-11eb-94e6-7c38e56dfbe6.png)

### 调试信息:

<details>
<summary>环境版本</summary>

```yaml
- requestId: ... # 如果在异常信息中显示请提供
- traceId: ... # 如果在异常信息中显示请提供
- 操作系统(OS): ... # 如: MacOS 11.2.3
- Node 版本: ... # 如: 12.20.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本: ... # 如: 3.7.2
- Framework 版本: ... # 如: 2.28.7
- SDK 版本: ... # 如: 2.3.2
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
{
  "name": "update-player-config",
  "version": "1.0.0",
  "description": "description",
  "main": "index.js",
  "author": "mmmm",
  "license": "MIT",
  "scripts": {
    "deploy": "sls deploy"
  },
  "dependencies": {
    "serverless": "^2.44.0"
  }
}

```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>
