### ISSUE TITLE
使用腾讯云 website 组件部署静态网站时多次失败

### ISSUE THREAD

**Issue by sonofmagic** [serverless/serverless-tencent#18]
### BUG 描述:

使用腾讯云 website 组件部署静态网站时多次失败

### 复现步骤:

serverless deploy

### 预期结果:

部署成功

### 实际结果:

当前操作已超出频次限制，请等待后重试 (reqId: 14d53cc6-caea-4717-8672-8068a31cb4ff) 

### 调试信息:

<details>
<summary>环境版本</summary>

```yaml
- requestId: 14d53cc6-caea-4717-8672-8068a31cb4ff
- 操作系统(OS): win10
- Node 版本: v14.17.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本: ... # 如: 3.12.0
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
app: icebreaker-top-ssg
name: icebreaker-top-ssg-doc
component: website
stage: dev
inputs:
  src:
    src: ./docs
    index: index.html
    error: index.html
  region: ap-shanghai
  bucket: icebreaker-top-ssg-bucket
  replace: false
  hosts:
    - host: icebreaker.top
      async: true
      onlyRefresh: true
      autoRefresh: true
      refreshCdn:
        urls:
          - 'http://icebreaker.top'
          - 'https://icebreaker.top'
    - host: www.icebreaker.top
      async: true
      onlyRefresh: true
      autoRefresh: true
      refreshCdn:
        urls:
          - 'http://www.icebreaker.top'
          - 'https://www.icebreaker.top'

```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>
