### ISSUE TITLE
serverless-tencent v3.21.6 部署提示cli版本过低，无法部署

### ISSUE THREAD

**Issue by nanhupatar** [serverless/serverless-tencent#198]
### BUG 描述:

Environment: darwin, node v16.13.1, tencent v3.21.6
```
1s › egg-dati › 系统检测到您使用的ServerlessCLI版本过低，请升级ServerlessCLI, npm install -g serverless, TraceId: 2982a472-d91d-4232-901f-811dc7393f9e, RequestId: 866ac84e-a964-4b86-8dd7-fc68917ae0ff 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 

macdeMac-mini:dati mac$ slt -v

serverless ⚡tencent 

serverless - tencent version: 3.21.6(npm) 
```
### 复现步骤:

1. 
2. 
3. 

### 调试信息:

<details>
<summary>环境版本</summary>

```yaml
- requestId: ... # 如果在异常信息中显示请提供
- traceId: ... # 如果在异常信息中显示请提供
- 操作系统(OS): ... # 如: MacOS 11.2.3
- Node 版本: ... # 如: 12.20.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本: ... # 如: 3.7.2
- Framework 版本: ... # 如: 2.28.7
- SDK 版本: ... # 如: 2.3.2
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>
