### ISSUE TITLE
An internal error has occurred. Retry your request, but if the problem persists, contact us

### ISSUE THREAD

**Issue by paihua514** [serverless/serverless-tencent#218]
### BUG 描述:
校验验证码时报错，问题如图：
![image](https://github.com/serverless/serverless-tencent/assets/39114242/64941cd3-d674-4d73-8756-7ad6133b9960)

参数：randstr=@s0X,ticket=tr03zVV5iCzo-FVkW2edch4GKm2haQWrmSgqMuxmde6XOeiNjec2TYXNamB6fnSd5_sCn9QYy2naF7kWuF6cfxJG8R0OjROUWH4_FkcwndEXfospCiXqEXSw0U5hMLOSR8tk

### 复现步骤:

1. 
2. 
3. 

### 调试信息:

<details>
<summary>环境版本</summary>

```yaml
- requestId: ... # 如果在异常信息中显示请提供
- traceId: ... # 如果在异常信息中显示请提供
- 操作系统(OS): ... # 如: MacOS 11.2.3
- Node 版本: ... # 如: 12.20.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本: ... # 如: 3.7.2
- Framework 版本: ... # 如: 2.28.7
- SDK 版本: ... # 如: 2.3.2
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>
