### ISSUE TITLE
在输入sis deploy时报错6s » Serverless » getaddrinfo ENOTFOUND 7890

### ISSUE THREAD

**Issue by Bai-soda** [serverless/serverless-tencent#45]
### 复现步骤:输入sis deploy

1. 打开cmd
2. 进入项目根目录下
3. sis deploy

### 调试信息:

<details>
<summary>环境版本</summary>

```yaml
- requestId: ... # 如果在异常信息中显示请提供
- traceId: ... # 如果在异常信息中显示请提供
- 操作系统(OS):win10 ... # 如: MacOS 11.2.3
- Node 版本:v16.6.2 ... # 如: 12.20.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本:3.17.1 ... # 如: 3.7.2
- Framework 版本: ... # 如: 2.28.7
- SDK 版本: ... # 如: 2.3.2
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
#组件信息
app: bilibili
component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: BiliExp # (必填) 创建的实例名称，请修改成您的实例名称

#B站自动操作
inputs:
  name: ${app}-BiliExp #函数名称
  #namespace: bilibili
  src: ./  #代码路径
  handler: BiliExp.main #入口
  runtime: Python3.6 # 云函数运行时的环境
  region: ap-guangzhou # 云函数所在区域
  description: 'B站经验脚本'
  timeout: 900
  events: # 触发器
    - timer: # 定时触发器
        name: timer-${name} #触发器名称，默认timer-${name}-${stage}
        parameters:
          cronExpression: '0 0,30 12-15,21-23 * * * *' #中午12点-15点、晚上21点-23点的0分或30分
          enable: true
```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>
