### ISSUE TITLE
新增flask应用，在自动构建其scf函数时，显示部署失败

### ISSUE THREAD

**Issue by wx2020** [serverless/serverless-tencent#85]
### BUG 描述:

新增flask应用，在自动构建其scf函数时，显示部署失败
### 复现步骤:
如上
### 预期结果:

部署成功

### 实际结果:

部署失败

### 调试信息:

应用 sms-api 部署失败，构建ID：13406962，请重新部署
![image](https://user-images.githubusercontent.com/35266946/144042763-1c39f4e0-4d35-485c-8e45-46b0829c4c1e.png)

[2021-11-30 19:46:04]  Error: SCF 函数名称(http-flask-W0qIO2bt-)命名不符合规则。 只能包含字母、数字、下划线、连字符，以字母开头，以数字或字母结尾，2~60个字符
![image](https://user-images.githubusercontent.com/35266946/144042694-094655c2-c2b9-4bb6-bc3d-8827f8951f19.png)

<details>
<summary>环境版本</summary>

```yaml
- requestId: ... # 如果在异常信息中显示请提供
- traceId: ... # 如果在异常信息中显示请提供
- 操作系统(OS): ... # 如: MacOS 11.2.3
- Node 版本: ... # 如: 12.20.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本: ... # 如: 3.7.2
- Framework 版本: ... # 如: 2.28.7
- SDK 版本: ... # 如: 2.3.2
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>
