### ISSUE TITLE
Serverless 应用 选择中国香港时 创建新的应用时错误

### ISSUE THREAD

**Issue by bhsx** [serverless/serverless-tencent#9]
### BUG 描述:

Serverless 应用 选择中国香港 新建flask应用时错误

### 复现步骤:

1.选择Serverless 应用
2. 新建应用
3. 选择 应用模板 和 快速部署一个 Flask 框架
4. 选择输入应用名和选择地域为中国香港

### 预期结果:

创建成功

### 实际结果:

Downloading code
Initializing node.js environment
Installing plugins
Installing dependencies
Processing serverless config files
Deploying serverless project
[2021-04-26 07:48:16] + serverless deploy --debug --force
[2021-04-26 07:48:17] 正在初始化...
[2021-04-26 07:48:17] Action: "deploy" - Stage: "prod" - App: "zycz" - Instance: "flask-18wHkdiQq"
[2021-04-26 07:48:20] 准备中...
[2021-04-26 07:48:28] 上传中...
[2021-04-26 07:48:28] 部署中...
[2021-04-26 07:48:43] 
[2021-04-26 07:48:43]  Error: 参数 `ExclusiveSetName`错误。 (reqId: 43558575-6f00-4ab2-b10d-d9e12fa395ae)
[2021-04-26 07:48:43]     at errorHandler (/var/user/node_modules/tencent-component-toolkit/lib/modules/apigw/apis.js:49:19)
[2021-04-26 07:48:43]     at Object.<anonymous> (/var/user/node_modules/tencent-component-toolkit/lib/utils/api.js:50:32)
[2021-04-26 07:48:43]     at Generator.next (<anonymous>)
[2021-04-26 07:48:43]     at fulfilled (/var/user/node_modules/tencent-component-toolkit/lib/utils/api.js:5:58)
[2021-04-26 07:48:43]     at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-04-26 07:48:43] 
[2021-04-26 07:48:43] 24s › flask-18wHkdiQq › 参数 `ExclusiveSetName`错误。 (reqId: 43558575-6f00-4ab2-b10d-d9e12fa395ae) 
[2021-04-26 07:48:43] 
[2021-04-26 07:48:43]   帮助文档: https://cloud.tencent.com/document/product/1154/39270 
[2021-04-26 07:48:43]   BUG提交: https://github.com/serverless/serverless-tencent/issues 
[2021-04-26 07:48:43]   问答社区: https://github.com/serverless/serverless-tencent/discussions 
[2021-04-26 07:48:43] 
[2021-04-26 07:48:43] 
[2021-04-26 07:48:43] 
script returned exit code 1

**Comment by ole3021** [comment]
@bhsx  上面这个问题我们今天已经修复了，然后在我本地测试过程中没有复现这个问题，是可以成功部署到香港地区的。 

麻烦你在尝试一下 如果问题还在，麻烦再提供一下更多的信息以便我们进一步debug。

* 请使用 `npm upgrade -g serverless` 更新到最新版的serverless CLI

这是我部署的结果，可以成功的将flask项目部署到香港区域(网关是香港地区的 xxx.hk.apigw.tencentcs.com)
```sh
serverless ⚡framework
Action: "deploy" - Stage: "dev" - App: "iss-flask-honkong-2835b5aa" - Instance: "flask-starter"

region: ap-hongkong
scf: 
  functionName: flask_component_xg3osu
  runtime:      Python3.6
  namespace:    default
  lastVersion:  $LATEST
  traffic:      1
apigw: 
  serviceId:   service-3zifuv9e
  subDomain:   service-3zifuv9e-1302533238.hk.apigw.tencentcs.com
  environment: release
  url:         https://service-3zifuv9e-1302533238.hk.apigw.tencentcs.com/release/

应用控制台: https://console.cloud.tencent.com/ssr/detail?stageName=dev&appName=iss-flask-honkong-2835b5aa&instanceName=flask-starter&stageList=dev

36s › flask-starter › 执行成功
```

以下是我的配置文件
```yml
component: flask # (required) name of the component. In that case, it's flask.
name: flask-starter # (required) name of your flask component instance.
app: iss-flask-honkong-2835b5aa # (optional) serverless dashboard app. default is the same as the name property.

inputs:
  src:
    # TODO: 安装python项目依赖到项目当前目录
    hook: "pip3 install -r requirements.txt -t ./"
    dist: ./ # (optional) path to the source folder. default is a hello world app.
    exclude:
      - .env
  region: ap-hongkong
  runtime: Python3.6
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
```
